### ISSUE TITLE
可以提供graphite的监控配置吗

### ISSUE THREAD

**Issue by Ants2GitHub** [qunarcorp/qmq#118]
**问题描述**
qmq-metrics-prometheus 接入 graphite启动异常

**环境配置**
monitor.port=3333
monitor.type=graphite
graphite.host=172.31.110.3
graphite.port=8000

**复现步骤**
graphite测报错：
[31/Aug/2020 11:51:49] code 400, message Bad request version ('1598845909')
[31/Aug/2020 11:51:49] "actorSystemQueue_qmq_meta 0.0 1598845909" 400 -
[31/Aug/2020 11:51:50] code 400, message Bad request version ('1598845910')
[31/Aug/2020 11:51:50] "sendMessageTaskInvokeCount 28.0 1598845910" 400 -

**实际输出结果**
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid metric name: message-logLag
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry.cacheFor(PrometheusQmqMetricRegistry.java:73)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry.newGauge(PrometheusQmqMetricRegistry.java:78)
	at qunar.tc.qmq.metrics.Metrics.gauge(Metrics.java:43)
	at qunar.tc.qmq.monitor.QMon.replayLag(QMon.java:357)
	at qunar.tc.qmq.store.LogIterateService.<init>(LogIterateService.java:53)
	at qunar.tc.qmq.delay.DefaultDelayLogFacade.<init>(DefaultDelayLogFacade.java:75)
	at qunar.tc.qmq.delay.startup.ServerWrapper.init(ServerWrapper.java:102)
	at qunar.tc.qmq.delay.startup.ServerWrapper.start(ServerWrapper.java:80)
	at qunar.tc.qmq.delay.container.Bootstrap.main(Bootstrap.java:27)
Caused by: java.lang.IllegalArgumentException: Invalid metric name: message-logLag
	at io.prometheus.client.Collector.checkMetricName(Collector.java:182)
	at io.prometheus.client.SimpleCollector.<init>(SimpleCollector.java:164)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqGauge.<init>(PrometheusQmqGauge.java:29)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqGauge$Builder.create(PrometheusQmqGauge.java:60)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry$GuageKey.create(PrometheusQmqMetricRegistry.java:159)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry$GuageKey.create(PrometheusQmqMetricRegistry.java:152)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry$1.load(PrometheusQmqMetricRegistry.java:46)
	at qunar.tc.qmq.metrics.prometheus.PrometheusQmqMetricRegistry$1.load(PrometheusQmqMetricRegistry.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 13 more

**期望输出结果**

**Comment by yuyijq** [comment]
prometheus的指标名称不允许出现横线，有个监控指标名称标记错了，已经修复
